version: 2
jobs:
  setup:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    working_directory: ~/repo

    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - save_cache:
          paths:
            - ~/src
            - ~/build.gradle
          key: code-cache-{{ .Environment.CIRCLE_SHA1 }}
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    working_directory: ~/repo

    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb

    steps:
      - restore_cache:
          key: code-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: ./gradlew build testClasses -x test

workflows:
  version: 2
  workflow:
    jobs:
      - setup
      - build: 
          requires:
            - setup