version: 2
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  setup:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    working_directory: ~/repo

    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - save_cache:
          paths:
            - ~
          key: code-cache-{{ .Environment.CIRCLE_SHA1 }}

  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    working_directory: ~/repo

    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb

    steps:
      - restore_cache:
          key: code-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: ./gradlew build testClasses integrationTestClasses end2endClasses -x test

  "unit test":
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    working_directory: ~/repo

    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb

    steps:
      - restore_cache:
          key: code-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: ./gradlew test -i
      - save_cache:
          paths:
            -./build/jacoco/test.exec
          key: jacoco-test-{{ .Environment.CIRCLE_SHA1 }}

  "integration test":
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    working_directory: ~/repo

    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb

    steps:
      - restore_cache:
          key: code-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: ./gradlew integrationTest -i
      - save_cache:
          paths:
            -./build/jacoco/integrationTest.exec
          key: jacoco-integrationTest-{{ .Environment.CIRCLE_SHA1 }}

  "end to end test":
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    working_directory: ~/repo

    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb

    steps:
      - restore_cache:
          key: code-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: ./gradlew end2end -i
      - save_cache:
          paths:
            -./build/jacoco/end2end.exec
          key: jacoco-end2end-{{ .Environment.CIRCLE_SHA1 }}

  codecov:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: code-cache-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: jacoco-test-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: jacoco-integrationTest-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: jacoco-end2end-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd build/jacoco
      - run: ls -la


workflows:
  version: 2
  workflow:
    jobs:
      - setup
      - build: 
          requires:
            - setup
      - "unit test":
          requires:
            - build
      - "integration test":
          requires:
            - build
      - "end to end test":
          requires:
            - build
      - codecov:
          requires:
            - "unit test"
            - "integration test"
            - "end to end test"