CREATE TABLE IF NOT EXISTS EMAIL_IDENTITIES (
    id uuid NOT NULL PRIMARY KEY,
    email VARCHAR,
    password VARCHAR
);

ALTER TABLE ACCOUNTS
    ADD COLUMN email_identity_id uuid REFERENCES EMAIL_IDENTITIES (id);

INSERT INTO EMAIL_IDENTITIES
SELECT gen_random_uuid(), email, password
FROM ACCOUNTS;

UPDATE ACCOUNTS
SET email_identity_id = EMAIL_IDENTITIES.id
FROM EMAIL_IDENTITIES
WHERE EMAIL_IDENTITIES.email = ACCOUNTS.email;