version: '3.3'

services:
  db:
    container_name: dumbbell-postgres
    image: postgres
    restart: always
    env_file:
      - ../.env
    ports:
      - 5432:5432
  adminer:
    container_name: adminerino
    image: adminer
    restart: always
    ports:
      - 8083:8080