version: '3.3'

services:
  db:
    container_name: dumbbell-postgres
    image: postgres
    restart: always
    env_file:
      - ../.env
    ports:
      - 5432:5432
  app:
    container_name: dumbbell-be-container
    image: dumbbell-be-image
    restart: always
    env_file:
      - ../.env
    ports:
      - 8080:8080
    depends_on:
      - db
  adminer:
    container_name: adminerino
    image: adminer
    restart: always
    ports:
      - 8083:8080